<?php
error_reporting(E_ALL);
date_default_timezone_set('Asia/Shanghai');
set_time_limit(0);

return [
    ["http://stockdata.stock.hexun.com/zlkp/s000002.shtml", '万科A'],
    ["http://stockdata.stock.hexun.com/zlkp/s601988.shtml", '中国银行'],
    ["http://stockdata.stock.hexun.com/zlkp/s600166.shtml", '福田汽车'],
    ["http://stockdata.stock.hexun.com/zlkp/s002181.shtml", '粤传媒'],
    ["http://stockdata.stock.hexun.com/zlkp/s600810.shtml", '神马股份'],
    ["http://stockdata.stock.hexun.com/zlkp/s601989.shtml", '中国重工'],
    ["http://stockdata.stock.hexun.com/zlkp/s000738.shtml", '中航动控'],
    ["http://stockdata.stock.hexun.com/zlkp/s601398.shtml", '工商银行'],
    ["http://stockdata.stock.hexun.com/zlkp/s002594.shtml", '比亚迪'],
    ["http://stockdata.stock.hexun.com/zlkp/s600312.shtml", '平高电气'],
    ["http://stockdata.stock.hexun.com/zlkp/s600029.shtml", '南方航空'],
    ["http://stockdata.stock.hexun.com/zlkp/s000958.shtml", '东方能源'],
    ["http://stockdata.stock.hexun.com/zlkp/s600628.shtml", '新世界'],
    ["http://stockdata.stock.hexun.com/zlkp/s600836.shtml", '界龙实业'],
    ["http://stockdata.stock.hexun.com/zlkp/s002548.shtml", '金新农'],
    ["http://stockdata.stock.hexun.com/zlkp/s002429.shtml", '兆驰股份'],
    ["http://stockdata.stock.hexun.com/zlkp/s300073.shtml", '当升科技'],
    ["http://stockdata.stock.hexun.com/zlkp/s002093.shtml", '国脉科技'],
    //["http://stockdata.stock.hexun.com/zlkp/s002638.shtml", '勤上光电'],
    ["http://stockdata.stock.hexun.com/zlkp/s601929.shtml", '吉视传媒'],
    ["http://stockdata.stock.hexun.com/zlkp/s600016.shtml", '民生银行'],
    ["http://stockdata.stock.hexun.com/zlkp/s002342.shtml", '巨力索具'],
    ["http://stockdata.stock.hexun.com/zlkp/s600059.shtml", '古越龙山'],
    ["http://stockdata.stock.hexun.com/zlkp/s600193.shtml", '创兴资源'],
    ["http://stockdata.stock.hexun.com/zlkp/s000626.shtml", '如意集团'],
    ["http://stockdata.stock.hexun.com/zlkp/s002089.shtml", '新海宜'],
    ["http://stockdata.stock.hexun.com/zlkp/s000830.shtml", '鲁西化工'],
    ["http://stockdata.stock.hexun.com/zlkp/s000503.shtml", '海虹控股'],
    ["http://stockdata.stock.hexun.com/zlkp/s600020.shtml", '中原告诉'],
    ["http://stockdata.stock.hexun.com/zlkp/s002027.shtml", '七喜控股'],
    ["http://stockdata.stock.hexun.com/zlkp/s002043.shtml", '兔宝宝'],
    ["http://stockdata.stock.hexun.com/zlkp/s002030.shtml", '达安基因'],
    ["http://stockdata.stock.hexun.com/zlkp/s000889.shtml", '茂业物流'],
    ["http://stockdata.stock.hexun.com/zlkp/s002007.shtml", '华兰生物'],
    ["http://stockdata.stock.hexun.com/zlkp/s000970.shtml", '中科三环'],
    ["http://stockdata.stock.hexun.com/zlkp/s600894.shtml", '广日股份'],
    ["http://stockdata.stock.hexun.com/zlkp/s600432.shtml", '吉恩镍业'],
    ["http://stockdata.stock.hexun.com/zlkp/s600642.shtml", '申能股份'],
    ["http://stockdata.stock.hexun.com/zlkp/s000725.shtml", '京东方A'],
    ["http://stockdata.stock.hexun.com/zlkp/s000973.shtml", '佛塑科技'],
    ["http://stockdata.stock.hexun.com/zlkp/s002147.shtml", '方圆支承'],
    ["http://stockdata.stock.hexun.com/zlkp/s600609.shtml", '金杯汽车'],
    ["http://stockdata.stock.hexun.com/zlkp/s600649.shtml", '城投控股'],
    ["http://stockdata.stock.hexun.com/zlkp/s002231.shtml", '奥维通信'],
    ["http://stockdata.stock.hexun.com/zlkp/s002355.shtml", '兴民钢圈'],
    ["http://stockdata.stock.hexun.com/zlkp/s000402.shtml", '金融街'],
    ["http://stockdata.stock.hexun.com/zlkp/s000533.shtml", '万家乐'],
    ["http://stockdata.stock.hexun.com/zlkp/s002442.shtml", '龙星化工'],
    ["http://stockdata.stock.hexun.com/zlkp/s600143.shtml", '金发科技'],
    ["http://stockdata.stock.hexun.com/zlkp/s601390.shtml", '中国中铁'],
    ["http://stockdata.stock.hexun.com/zlkp/s600615.shtml", '丰华股份'],
    ["http://stockdata.stock.hexun.com/zlkp/s600485.shtml", '信威集团'],
    ["http://stockdata.stock.hexun.com/zlkp/s600279.shtml", '重庆港九'],
    ["http://stockdata.stock.hexun.com/zlkp/s002549.shtml", '凯美特气'],
    ["http://stockdata.stock.hexun.com/zlkp/s600821.shtml", '津劝业'],
    ["http://stockdata.stock.hexun.com/zlkp/s600820.shtml", '隧道股份'],
    ["http://stockdata.stock.hexun.com/zlkp/s600851.shtml", '海欣股份'],
    ["http://stockdata.stock.hexun.com/zlkp/s000868.shtml", '安凯客车'],
];